### ISSUE TITLE
Mobile searches don't work

### ISSUE THREAD

**Issue by chekyal** [pabl1ku/Microsoft-Rewards-Extension#1]
Tabs open, but Microsoft Rewards doesn't count
![image](https://user-images.githubusercontent.com/91327680/223173120-d006256b-67b0-4eee-9229-1e24b3d2355f.png)

**Comment by pabl1ku** [comment]
Hello, do you have desktop and mobile search enabled?

![Sin título](https://user-images.githubusercontent.com/115459058/223177328-d3275c5c-0183-4218-a47a-4853d47353fd.png)

Today I have done my daily searches and I have had no problems at all as you can see in this picture

![Sin títtulo](https://user-images.githubusercontent.com/115459058/223177697-e478b1bf-896d-49f9-a38b-3b1cfe392737.png)

In any case, there may have been a bug, to fix this, change the search option from desktop and mobile to mobile and try to see if it works, if it still does not work, come back here!

Best regards and I hope it has helped you!

**Comment by chekyal** [comment]
Hello, sadly didn't work.
![image](https://user-images.githubusercontent.com/91327680/223184782-e81c8f30-4801-4f4c-ab3a-1085ed9b147c.png)
![image](https://user-images.githubusercontent.com/91327680/223184953-d34c59b4-c3c1-457a-abfe-986098e243bd.png)

**Comment by pabl1ku** [comment]
Hi, are you by any chance using VPN to get more points? Don't worry about the question, I understand that if you use VPN this extension doesn't usually work.

**Comment by pabl1ku** [comment]
Oh, I understand. In this case, you could reinstall the extension, I think it would work with what you are telling me.
